const data = {
  banho: "Si",
  campamento: "Si",
  cerca_a_area_deforestada: "No",
  cerca_a_carretera: "No",
  codigo_ant: "CNI-14-LSG",
  codigo_de_la_parcela: "LS14",
  combustible_para_transporte: "Si",
  dap: "1.32",
  dentro_de_area_deforestada: "No",
  departamento: "Madre de Dios",
  distrito: "Tambopata",
  dni_ruc: "04803949",
  edad: 71,
  en_estrada: "Si",
  este: "468070",
  ht: "32.00",
  juvenil_o_maduro: "Maduro",
  lianas: "No",
  nombre_cientifico: "Bertholletia Excelsa",
  nombre_del_area_castanera: "Luis",
  norte: "8589688",
  nro_celular: "913761451",
  nro_de_arbol: 14,
  nro_de_contrato: "RGR-N 019-2020-GOREMAD-GRFFS",
  nro_de_estrada: 1,
  observaciones: "Arbol nuevo, falta tarjeta QR",
  produccion_latas: "2.00",
  productivo: "Si",
  provincia: "Tambopata",
  rama_caida: "No",
  razon_social: "LUIS SEHUE GUZMAN",
  realiza_quemas: "No",
  sano_o_enfermo: "Sano",
  sector: "CN. INFIERNO",
  semillero: "No",
};
